spring:
  data:
    redis:
      port: 6379
      host: 192.168.100.128
      password: 123321
      # 连接池配置
      lettuce:
        pool:
          max-active: 8      # 最大连接数
          max-idle: 8        # 最大空闲连接数
          min-idle: 0        # 最小空闲连接数
          max-wait: -1ms     # 最大等待时间

      # 超时配置
      timeout: 2000ms        # 连接超时时间
      # 数据库索引
      database: 3
      # 序列化配置
      Jedis:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 0
  datasource:
    url: jdbc:mysql://localhost:3306/wenji
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: qwen-max
          temperature: 0.8
          max-tokens: 200

logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.example.ai: debug
mybatis:
  configuration:
    map-underscore-to-camel-case: true
